// Choose login
POST https://localhost:7157/auth/login
Content-Type: application/json

{ "Username" : "Maanz", "Password" : "1FinePassword!" }

###

GET https://localhost:7157/test/authorized
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJKV1RTZXJ2aWNlQWNjZXNzVG9rZW4iLCJqdGkiOiI5ZDVjOTg4OC0zOWFiLTQ5MjUtYTc4ZS0yNzdiYWRkNTg5ZDMiLCJpYXQiOiIwOC0xMS0yMDIyIDEzOjMxOjAyIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZSI6Ik1hYW56IiwiRGlzcGxheU5hbWUiOiJBbGV4YW5kZXIgUmVkZGVyIiwiU2VjdXJpdHlMZXZlbCI6IjQiLCJJZCI6IjYiLCJleHAiOjE2Njc5MTc4NjIsImlzcyI6IkpXVEF1dGhlbnRpY2F0aW9uU2VydmVyIiwiYXVkIjoiSldUU2VydmljZUJsYXpvcldhc21DbGllbnQifQ.Y942pe8wCcETjqmM8f582h4YHShJ-vp36rpljO4LCUIhH9x96NfKYELCUV3eyVTAYiSKW4mseoIjhzUTL7ZyKg

###

GET https://localhost:7157/test/securitylevel
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJKV1RTZXJ2aWNlQWNjZXNzVG9rZW4iLCJqdGkiOiI1N2Y5ZTAyZS00Nzc5LTRkMTMtYWNhNC1lNGMxMDg4YzdmYjgiLCJpYXQiOiIwOC0xMS0yMDIyIDEzOjE3OjAyIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZSI6Ik1hYW56IiwiRGlzcGxheU5hbWUiOiJBbGV4YW5kZXIgUmVkZGVyIiwiU2VjdXJpdHlMZXZlbCI6IjQiLCJJZCI6IjYiLCJleHAiOjE2Njc5MTcwMjIsImlzcyI6IkpXVEF1dGhlbnRpY2F0aW9uU2VydmVyIiwiYXVkIjoiSldUU2VydmljZUJsYXpvcldhc21DbGllbnQifQ.4jLRypeTUD9-_C9Pb9NEm26hHb-H9gJ8pf6ZF-Xkht46QKOpMxySwcyBLGYgfIfHWlKnDSpbs11QfJJlVnPd0A

###

GET https://localhost:7157/Test/allowanon
